config/routes.rb
LosPredictor::Application.routes.draw do
  resources :hospitalizations

  resources :patients

  resources :users

  

end

app/models/hospitalization.rb
class Hospitalization < ActiveRecord::Base
	belongs_to :patient
end

app/controllers/hospitalizations_controller.rb
class HospitalizationsController < ApplicationController
  before_action :set_hospitalization, only: [:show, :edit, :update, :destroy]

  # GET /hospitalizations
  # GET /hospitalizations.json
  def index
    @hospitalizations = Hospitalization.all
  end

  # GET /hospitalizations/1
  # GET /hospitalizations/1.json
  def show
  end

  # GET /hospitalizations/new
  def new
    @hospitalization = Hospitalization.new
  end

  # GET /hospitalizations/1/edit
  def edit
  end

  # POST /hospitalizations
  # POST /hospitalizations.json
  def create
    @hospitalization = Hospitalization.new(hospitalization_params)

    respond_to do |format|
      if @hospitalization.save
        format.html { redirect_to @hospitalization, notice: 'Hospitalization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hospitalization }
      else
        format.html { render action: 'new' }
        format.json { render json: @hospitalization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitalizations/1
  # PATCH/PUT /hospitalizations/1.json
  def update
    respond_to do |format|
      if @hospitalization.update(hospitalization_params)
        format.html { redirect_to @hospitalization, notice: 'Hospitalization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hospitalization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitalizations/1
  # DELETE /hospitalizations/1.json
  def destroy
    @hospitalization.destroy
    respond_to do |format|
      format.html { redirect_to hospitalizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospitalization
      @hospitalization = Hospitalization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospitalization_params
      params.require(:hospitalization).permit(:admission_date, :current_days, :current_estimated_los, :current_estimated_discharge_date, :estimated_los_at_admission, :estimated_discharge_date_at_admission, :physician_estimate_discharge_date, :age_at_admission, :age_group_at_admission, :most_responsible_diagnosis_at_admission, :most_responsible_diagnosis_group_at_admission, :admitting_program, :patient_id)
    end
end

app/helpers/hospitalizations_helper.rb
module HospitalizationsHelper
end

app/views/hospitalizations/_form.html.erb
<%= form_for(@hospitalization) do |f| %>
  <% if @hospitalization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospitalization.errors.count, "error") %> prohibited this hospitalization from being saved:</h2>

      <ul>
      <% @hospitalization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.number_field :patient_id %>
  </div>

  <div class="field">
    <%= f.label :admission_date %><br>
    <%= f.date_select :admission_date %>
  </div>
  <div class="field">
    <%= f.label :current_days %><br>
    <%= f.number_field :current_days %>
  </div>
  <div class="field">
    <%= f.label :current_estimated_los %><br>
    <%= f.number_field :current_estimated_los %>
  </div>
  <div class="field">
    <%= f.label :current_estimated_discharge_date %><br>
    <%= f.date_select :current_estimated_discharge_date %>
  </div>
  <div class="field">
    <%= f.label :estimated_los_at_admission %><br>
    <%= f.number_field :estimated_los_at_admission %>
  </div>
  <div class="field">
    <%= f.label :estimated_discharge_date_at_admission %><br>
    <%= f.date_select :estimated_discharge_date_at_admission %>
  </div>
  <div class="field">
    <%= f.label :physician_estimate_discharge_date %><br>
    <%= f.date_select :physician_estimate_discharge_date %>
  </div>
  <div class="field">
    <%= f.label :age_at_admission %><br>
    <%= f.number_field :age_at_admission %>
  </div>
  <div class="field">
    <%= f.label :age_group_at_admission %><br>
    <%= f.text_field :age_group_at_admission %>
  </div>
  <div class="field">
    <%= f.label :most_responsible_diagnosis_at_admission %><br>
    <%= f.text_field :most_responsible_diagnosis_at_admission %>
  </div>
  <div class="field">
    <%= f.label :most_responsible_diagnosis_group_at_admission %><br>
    <%= f.text_field :most_responsible_diagnosis_group_at_admission %>
  </div>
  <div class="field">
    <%= f.label :admitting_program %><br>
    <%= f.text_field :admitting_program %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospitalizations/edit.html.erb
<h1>Editing hospitalization</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospitalization %> |
<%= link_to 'Back', hospitalizations_path %>

app/views/hospitalizations/index.html.erb
<h1>Listing hospitalizations</h1>

<table>
  <thead>
    <tr>
      <th>Admission date</th>
      <th>Current days</th>
      <th>Current estimated los</th>
      <th>Current estimated discharge date</th>
      <th>Estimated los at admission</th>
      <th>Estimated discharge date at admission</th>
      <th>Physician estimate discharge date</th>
      <th>Age at admission</th>
      <th>Age group at admission</th>
      <th>Most responsible diagnosis at admission</th>
      <th>Most responsible diagnosis group at admission</th>
      <th>Admitting program</th>
      <th>Patient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitalizations.each do |hospitalization| %>
      <tr>
        <td><%= hospitalization.admission_date %></td>
        <td><%= hospitalization.current_days %></td>
        <td><%= hospitalization.current_estimated_los %></td>
        <td><%= hospitalization.current_estimated_discharge_date %></td>
        <td><%= hospitalization.estimated_los_at_admission %></td>
        <td><%= hospitalization.estimated_discharge_date_at_admission %></td>
        <td><%= hospitalization.physician_estimate_discharge_date %></td>
        <td><%= hospitalization.age_at_admission %></td>
        <td><%= hospitalization.age_group_at_admission %></td>
        <td><%= hospitalization.most_responsible_diagnosis_at_admission %></td>
        <td><%= hospitalization.most_responsible_diagnosis_group_at_admission %></td>
        <td><%= hospitalization.admitting_program %></td>
        <td><%= hospitalization.patient_id %></td>
        <td><%= link_to 'Show', hospitalization %></td>
        <td><%= link_to 'Edit', edit_hospitalization_path(hospitalization) %></td>
        <td><%= link_to 'Destroy', hospitalization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospitalization', new_hospitalization_path %>

app/views/hospitalizations/new.html.erb
<h1>New hospitalization</h1>

<%= render 'form' %>

<%= link_to 'Back', hospitalizations_path %>

app/views/hospitalizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admission date:</strong>
  <%= @hospitalization.admission_date %>
</p>

<p>
  <strong>Current days:</strong>
  <%= @hospitalization.current_days %>
</p>

<p>
  <strong>Current estimated los:</strong>
  <%= @hospitalization.current_estimated_los %>
</p>

<p>
  <strong>Current estimated discharge date:</strong>
  <%= @hospitalization.current_estimated_discharge_date %>
</p>

<p>
  <strong>Estimated los at admission:</strong>
  <%= @hospitalization.estimated_los_at_admission %>
</p>

<p>
  <strong>Estimated discharge date at admission:</strong>
  <%= @hospitalization.estimated_discharge_date_at_admission %>
</p>

<p>
  <strong>Physician estimate discharge date:</strong>
  <%= @hospitalization.physician_estimate_discharge_date %>
</p>

<p>
  <strong>Age at admission:</strong>
  <%= @hospitalization.age_at_admission %>
</p>

<p>
  <strong>Age group at admission:</strong>
  <%= @hospitalization.age_group_at_admission %>
</p>

<p>
  <strong>Most responsible diagnosis at admission:</strong>
  <%= @hospitalization.most_responsible_diagnosis_at_admission %>
</p>

<p>
  <strong>Most responsible diagnosis group at admission:</strong>
  <%= @hospitalization.most_responsible_diagnosis_group_at_admission %>
</p>

<p>
  <strong>Admitting program:</strong>
  <%= @hospitalization.admitting_program %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @hospitalization.patient_id %>
</p>

<%= link_to 'Edit', edit_hospitalization_path(@hospitalization) %> |
<%= link_to 'Back', hospitalizations_path %>