config/routes.rb
LosPredictor::Application.routes.draw do
  resources :hospitalizations

  resources :patients

  resources :users

  

end

app/models/patient.rb
class Patient < ActiveRecord::Base

		has_many :hospitalizations

	 	validates :first_name, :presence => true, 
                          :length => {:minimum => 1, :maximum => 254}

	 	validates :last_name, :presence => true, 
                          :length => {:minimum => 1, :maximum => 254}

	 	validates :date_of_birth, :presence => true, 
                          :length => {:minimum => 1, :maximum => 254}
    
#    validate :date_of_birth_is_valid_datetime?                  
#		
#		private
#
#  	def date_of_birth_is_valid_datetime?
#    	if !date_of_birth.is_a?(Date)
#      	errors.add(:date_of_birth, 'must be a valid date') 
#    	end
#  	end

	 	validates :current_address, :presence => true, 
                          :length => {:minimum => 1, :maximum => 254}

	 	validates :current_telephone, :presence => true, 
                          :length => {:minimum => 1, :maximum => 254}

	 	validates :personal_health_number, :presence => true, 
                          :length => {:minimum => 1, :maximum => 254},
                          :uniqueness => true

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @patient }
      else
        format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:personal_health_number, :first_name, :last_name, :date_of_birth, :current_address, :current_telephone)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :personal_health_number %><br>
    <%= f.text_field :personal_health_number %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :current_address %><br>
    <%= f.text_field :current_address %>
  </div>
  <div class="field">
    <%= f.label :current_telephone %><br>
    <%= f.text_field :current_telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Personal health number</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Date of birth</th>
      <th>Current address</th>
      <th>Current telephone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.personal_health_number %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= patient.current_address %></td>
        <td><%= patient.current_telephone %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Personal health number:</strong>
  <%= @patient.personal_health_number %>
</p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @patient.date_of_birth %>
</p>

<p>
  <strong>Current address:</strong>
  <%= @patient.current_address %>
</p>

<p>
  <strong>Current telephone:</strong>
  <%= @patient.current_telephone %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>